enum Task {
    ExecuteCommand,
    UploadFile,
    DownloadFile,
    GetMeta,
    SetMeta,
}

//! Now:
//!             => task payload (taskId generated by taskserver)
//!             <= task execution result
//! Commander <==============> Executor 1
//!                            Executor 2
//!                            ...
///
//! Next
//!
//!            bi-dir channel
//! Commander <==============> Executor 1
//!                            Executor 2
//!                            ...
//!
//!
//! Protocol:
//!   Commander:
//!     open_channel(targets, task) -> channel_id
//!     send(channel_id, payload)?
//!     recv implicit by (channel_id, target, payload)
//!

//trait RPCTask {
//    fn
//}



