[package]
name = "grpc-service"
version = "0.9.0"
authors = ["Philippe GASSMANN <philoops@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tonic={git="https://github.com/zenria/tonic.git", features=["tokio-rustls", "tls"], branch = "master" }
tonic={version="0.1.0", features=["tokio-rustls", "tls"] }
prost = "0.6"
async-stream = "0.1.2"
bytes = "0.4"

[build-dependencies]
#tonic={git="https://github.com/zenria/tonic.git", features=["tokio-rustls", "tls"], branch = "master" }
tonic-build="0.1.0"
