[package]
name = "grpc-service"
version = "0.1.0"
authors = ["Philippe GASSMANN <philoops@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic="0.1.0-alpha.5"
prost = "0.5"
async-stream = "0.1.2"
bytes = "0.4"

[build-dependencies]
tonic-build = "0.1.0-alpha.5"
