[package]
name = "grpc-service"
version = "0.19.0"
authors = ["Philippe GASSMANN <philoops@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic={version="0.2", features=["tokio-rustls", "tls"] }
prost = "0.6"
async-stream = "0.1.2"
bytes = "0.4"
thiserror="1"

[build-dependencies]
tonic-build="0.2"
