[package]
name = "funtonic"
version = "0.6.0"
authors = ["Philippe GASSMANN <philoops@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic={git="https://github.com/zenria/tonic.git", features=["tokio-rustls", "tls"], branch = "tcp_keepalive" }
rand = "0.7.2"

tokio = "=0.2.0-alpha.6"
tokio-executor = "0.2.0-alpha.6"
tokio-sync = "0.2.0-alpha.6"
futures-core-preview = "=0.3.0-alpha.19"
futures-util-preview = "=0.3.0-alpha.19"
futures-sink-preview = "=0.3.0-alpha.19"
futures-channel-preview = {version="=0.3.0-alpha.19", features=["sink"]}
async-stream = "0.1.2"
crossbeam="0.7.2"
itertools = "0.8.0"
log="0.4"
serde = { version = "1.0.101", features = ["derive"] }
serde_yaml="0.8.11"
structopt = "0.3"
shellexpand = "1.0.0"
thiserror = "1.0"
anyhow = "1.0"
http="0.1"
os_info = "1.1"
rustbreak = {version="2.0.0-rc3", features=["yaml_enc"]}
query-parser = {path="../query-parser"}
grpc-service = {path="../grpc-service"}
