[package]
name = "funtonic"
version = "0.19.6"
authors = ["Philippe GASSMANN <philoops@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic={version="0.3", features=["tokio-rustls", "tls"] }
rand = "0.7.2"

tokio = {version="0.2", features=["full"]}
futures="0.3"
async-stream ="0.2.1"
crossbeam="0.7.3"
itertools = "0.9.0"
log="0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml="0.8"
serde_json="1.0"
structopt = "0.3"
shellexpand = "1.0.0"
thiserror = "1.0"
anyhow = "1.0"
http="0.2"
os_info = "2.0"
rustbreak = {git="https://github.com/zenria/rustbreak.git", branch="remove_failure", features=["yaml_enc", "ron_enc"]}
query-parser = {path="../query-parser"}
grpc-service = {path="../grpc-service"}
exec={path="../exec"}
ring="0.16"
prost="0.6"
chrono = "0.4"
base64="0.12"
bytes = "0.5.4"
get_if_addrs = "0.5"

[dev-dependencies]
tempfile = "3"
